# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802594c1700734657793b7b3d1f51020548ea82e5b2bbca0fb7c3aa10c901bbb2fdf7a42102412d04cd55e0d809e601772b8c8a2acd3efbc5adac2cb3a62b885

test:
  secret_key_base: 2d06556f4871d7f691cf77d954dd73ebd8876f41624f8dc862c08f416ad146a4fc54d592b66fdb67317a78b2d103bd0c830845c19f978a8bb84e6d7f848d42dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
